FROM gwul/sfm-base@sha256:81f3ecc962b9510604ea3dca9a385ba1012268fc07bf1496975f91a69817d939
MAINTAINER Justin Littman <justinlittman@gwu.edu>

ADD . /opt/sfm-ui/
WORKDIR /opt/sfm-ui
RUN pip install -r requirements/common.txt -r requirements/release.txt

#This is used to automatically create the admin user.
RUN pip install django-finalware==0.1.0

# Adds fixtures.
ADD docker/ui/fixtures.json /opt/sfm-setup/

ADD docker/ui/invoke_runserver.sh /opt/sfm-setup/
RUN chmod +x /opt/sfm-setup/invoke_runserver.sh

ADD docker/ui/setup_ui.sh /opt/sfm-setup/
RUN chmod +x /opt/sfm-setup/setup_ui.sh

ENV DJANGO_SETTINGS_MODULE=sfm.settings.docker_settings
ENV LOAD_FIXTURES=false
EXPOSE 8000

CMD ["/opt/sfm-setup/invoke_runserver.sh"]