FROM gwul/sfm-base@sha256:81f3ecc962b9510604ea3dca9a385ba1012268fc07bf1496975f91a69817d939
MAINTAINER Justin Littman <justinlittman@gwu.edu>

ADD . /opt/sfm-ui/
WORKDIR /opt/sfm-ui
RUN pip install -r requirements/common.txt -r requirements/release.txt

RUN pip install django-finalware==0.1.0

ADD docker/consumer/invoke_consumer.sh /opt/sfm-setup/
RUN chmod +x /opt/sfm-setup/invoke_consumer.sh

ENV DJANGO_SETTINGS_MODULE=sfm.settings.docker_settings
ENV LOAD_FIXTURES=false

CMD ["/opt/sfm-setup/invoke_consumer.sh"]