# Generated by Django 2.2.24 on 2021-10-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0023_auto_20181218_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='export_segment_size',
            field=models.BigIntegerField(blank=True, choices=[(100000, '100,000'), (250000, '250,000'), (500000, '500,000'), (1000000, '1,000,000'), (None, 'Single file'), (100, '100')], default=250000, null=True),
        ),
    ]
