# Generated by Django 2.2.24 on 2021-12-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0024_auto_20211021_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='harvest_type',
            field=models.CharField(choices=[('twitter_user_timeline', 'Twitter user timeline'), ('twitter_search', 'Twitter search'), ('twitter_filter', 'Twitter filter'), ('twitter_sample', 'Twitter sample'), ('twitter_academic_search', 'Twitter academic research'), ('twitter_search_2', 'Twitter search version 2'), ('twitter_user_timeline_2', 'Twitter user timeline version 2'), ('tumblr_blog_posts', 'Tumblr blog posts'), ('flickr_user', 'Flickr user'), ('weibo_timeline', 'Weibo timeline')], max_length=255),
        ),
        migrations.AlterField(
            model_name='credential',
            name='platform',
            field=models.CharField(choices=[('twitter', 'Twitter'), ('twitter2', 'Twitter version 2'), ('flickr', 'Flickr'), ('weibo', 'Weibo'), ('tumblr', 'Tumblr')], help_text='Platform name', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalcollection',
            name='harvest_type',
            field=models.CharField(choices=[('twitter_user_timeline', 'Twitter user timeline'), ('twitter_search', 'Twitter search'), ('twitter_filter', 'Twitter filter'), ('twitter_sample', 'Twitter sample'), ('twitter_academic_search', 'Twitter academic research'), ('twitter_search_2', 'Twitter search version 2'), ('twitter_user_timeline_2', 'Twitter user timeline version 2'), ('tumblr_blog_posts', 'Tumblr blog posts'), ('flickr_user', 'Flickr user'), ('weibo_timeline', 'Weibo timeline')], max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalcredential',
            name='platform',
            field=models.CharField(choices=[('twitter', 'Twitter'), ('twitter2', 'Twitter version 2'), ('flickr', 'Flickr'), ('weibo', 'Weibo'), ('tumblr', 'Tumblr')], help_text='Platform name', max_length=255),
        ),
    ]
