#!/bin/bash
# Extract the Dockerfile suffix from the repo name; need to do this because the DOCKERFILE_PATH variable is not defined when running this script in autobuild
# Remove the path from the repo name
DOCKERFILE_SUFFIX=${DOCKER_REPO##*/}
# Remove the sfm-twitter prefix to extract the name of the Dockerfile
DOCKERFILE_SUFFIX=${DOCKERFILE_SUFFIX#sfm-ui}
echo "Dockerfile PATH is ${DOCKERFILE_PATH}"
if [ $DOCKER_TAG == "master" ]
then
    docker build . --build-arg build_version=master -f "Dockerfile${DOCKERFILE_SUFFIX}" -t $IMAGE_NAME  
else
    docker build . -f "Dockerfile${DOCKERFILE_SUFFIX}" -t $IMAGE_NAME 
fi